ARG BASE_IMAGE=debian:stable-slim
FROM ${BASE_IMAGE}

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY ho-azure /usr/local/bin/ho-azure

ENTRYPOINT ["/usr/local/bin/ho-azure"]
