package render

import "harrierops-azure/internal/models"

var commandNarration = map[string]string{
	"whoami":              "Checking caller context and active subscription scope.",
	"inventory":           "Scoping the visible Azure resource footprint.",
	"automation":          "Reviewing Azure Automation accounts for identity, execution, webhook, worker, and secure-asset posture.",
	"app-credentials":     "Reviewing application and service-principal authentication material, federated trust, and visible current-identity control paths.",
	"devops":              "Reviewing Azure DevOps build definitions for trusted source inputs, visible injection surfaces, and Azure-facing change paths.",
	"app-services":        "Reviewing App Service runtime, hostname, identity, deployment, and config cues that change follow-on paths.",
	"acr":                 "Reviewing Azure Container Registry login, auth, network, and registry automation/trust cues.",
	"databases":           "Reviewing relational database server posture across Azure SQL, PostgreSQL Flexible, and MySQL Flexible.",
	"dcr":                 "Reviewing Data Collection Rules for collection, stream, destination, association, and transformation posture.",
	"diagnostic-settings": "Reviewing resource diagnostic settings for selected categories, metrics, destinations, and visible telemetry export posture.",
	"monitoring-sinks":    "Reviewing visible and declared monitoring destinations that DCRs and diagnostic settings can route telemetry toward.",
	"dns":                 "Reviewing public and private DNS zone inventory and namespace boundaries.",
	"aks":                 "Reviewing AKS control-plane endpoint, identity, auth posture, and Azure-side federation and addon cues.",
	"api-mgmt":            "Reviewing API Management gateway hostnames, identity, subscription, backend, and secret posture.",
	"appinsights":         "Reviewing Application Insights components and instrumented app settings for visible sampling, filtering, and logging posture.",
	"functions":           "Reviewing Function App runtime, trigger, storage binding, identity, and deployment posture.",
	"webjobs":             "Reviewing App Service WebJobs for background execution mode, rerun posture, and inherited app context.",
	"azure-ml":            "Reviewing Azure ML runtime, scheduling, endpoint, identity, and storage-linked workspace posture.",
	"event-grid":          "Reviewing Event Grid trigger routes, destination types, and visible execution-capable follow-on paths.",
	"logic-apps":          "Reviewing Logic Apps trigger posture, identity context, and safe downstream action relationships.",
	"container-apps-jobs": "Reviewing Container Apps Jobs trigger, execution, image, identity, secret, and registry posture.",
	"arm-deployments":     "Reviewing ARM deployment history for config exposure and linked content.",
	"endpoints":           "Mapping reachable IP and hostname surfaces from compute and web workloads.",
	"network-effective":   "Prioritizing likely public-IP reachability by combining visible endpoint and NSG evidence.",
	"env-vars":            "Reviewing App Service and Function App settings for exposed config paths and likely credential or secret follow-on.",
	"network-ports":       "Tracing likely inbound port exposure from visible NIC and subnet NSG rules.",
	"tokens-credentials":  "Correlating token-minting workloads, credential-bearing metadata paths, and the next likely follow-on.",
	"rbac":                "Collecting raw RBAC assignments across the current subscription.",
	"principals":          "Mapping visible principals, identity footholds, and follow-on candidates.",
	"permissions":         "Ranking principals by high-impact RBAC exposure and the next likely follow-on.",
	"privesc":             "Triage likely privilege-escalation and workload identity abuse paths.",
	"role-trusts":         "Reviewing high-signal identity trust edges and the clearest next review without implying delegated or admin consent.",
	"cross-tenant":        "Reviewing outside-tenant trust, delegated management, and tenant policy cues that most change control or pivot paths.",
	"lighthouse":          "Reviewing Azure Lighthouse delegations for cross-tenant management scope and high-impact access cues.",
	"auth-policies":       "Reviewing tenant auth controls that widen guest, consent, app-creation, or sign-in abuse paths.",
	"managed-identities":  "Mapping workload-linked managed identities and their visible privilege cues.",
	"keyvault":            "Reviewing Key Vault exposure, access-model weakness, and destructive leverage cues.",
	"resource-trusts":     "Correlating resource trust surfaces across public network and private-link paths.",
	"relay":               "Reviewing Azure Relay namespaces and Hybrid Connections for private-path rendezvous posture.",
	"storage":             "Checking storage exposure and network posture for likely data targets.",
	"snapshots-disks":     "Reviewing managed disks and snapshots for offline-copy, sharing/export, and encryption posture with highest-value targets first.",
	"nics":                "Enumerating NIC attachments, IP context, and network boundary references.",
	"workloads":           "Joining workload assets with identity context and visible ingress paths.",
	"vms":                 "Summarizing reachable compute assets and identity-bearing workloads.",
	"vm-extensions":       "Reviewing VM Extensions handler, source, protected-settings, and rerun posture.",
	"vmss":                "Reviewing Virtual Machine Scale Sets (VMSS) for fleet posture, identity, and frontend network cues.",
	"chains":              "Correlating grouped chain evidence with conservative cross-command joins.",
	"persistence":         "Walking the current identity through Azure-native persistence surfaces one service at a time.",
	"evasion":             "Walking the current identity through Azure-native evasion surfaces by visible truth-disruption posture.",
	"resourcehijacking":   "Walking the current identity through existing Azure resources that can be commandeered, redirected, replaced, or repurposed.",
	"pathmasking":         "Walking the current identity through Azure-native relay, proxy, and workflow surfaces that can blur caller-to-target paths.",
}

var commandCompactIntroHint = map[string]string{
	"aks":                 "table view is compact by design; the JSON artifact keeps the fuller visible field set",
	"acr":                 "table view is compact by design; the JSON artifact keeps the fuller visible field set",
	"api-mgmt":            "table view is compact by design; the JSON artifact keeps the fuller visible field set",
	"appinsights":         "table view is compact by design; the JSON artifact keeps the fuller visible field set",
	"dcr":                 "table view is compact by design; the JSON artifact keeps the fuller visible field set",
	"diagnostic-settings": "table view is compact by design; the JSON artifact keeps the fuller visible field set",
	"monitoring-sinks":    "table view is compact by design; the JSON artifact keeps the fuller visible field set",
	"env-vars":            "table view is compact by design; the JSON artifact keeps the fuller visible field set",
	"functions":           "table view is compact by design; the JSON artifact keeps the fuller visible field set",
	"azure-ml":            "table view is compact by design; the JSON artifact keeps the fuller visible field set",
	"event-grid":          "table view is compact by design; the JSON artifact keeps the fuller visible field set",
	"logic-apps":          "table view is compact by design; the JSON artifact keeps the fuller visible field set",
	"relay":               "table view is compact by design; the JSON artifact keeps the fuller visible field set",
	"tokens-credentials":  "table view is compact by design; the JSON artifact keeps the fuller visible field set",
	"vm-extensions":       "table view is compact by design; the JSON artifact keeps the fuller visible field set",
}

var chainsFamilyTableRenderers = map[string]func(models.ChainsOutput) string{
	"compute-control": chainsComputeControlTable,
	"credential-path": chainsCredentialPathTable,
	"deployment-path": chainsDeploymentPathTable,
	"escalation-path": chainsEscalationPathTable,
}
